/**
 * The consent gate, in JavaScript, agreeing with the Python one.
 *
 * `api/_consent.py` is the original and stays the original. This exists
 * because a Dynamic Worker's capabilities are composed at the edge from
 * a consent record, and the edge cannot call Python.
 *
 * ## Two gates is a real risk and this is how it is handled
 *
 * A second implementation of a safety decision is exactly the kind of
 * thing that drifts, and the drift is invisible: both sides pass their
 * own tests while disagreeing about whether an agent may ring somebody.
 *
 * So neither side owns the answers. `shared/consentVectors.json` was
 * GENERATED by running the real `may_contact`, and both test suites
 * read it — `api/test_consent_vectors.py` and `consent.test.mjs`. A
 * change to either implementation that alters a decision fails the
 * other language's suite, and a change to the fixture that does not
 * match Python fails immediately. There is no configuration in which
 * the two can quietly disagree.
 *
 * If you change a refusal here, regenerate the fixture from Python and
 * expect both suites to move together. If only one moves, one of them
 * is wrong.
 */

/** Channels a record can permit, and how a refusal names them. */
export const CHANNELS = {
	voice: "a phone call",
	whatsapp: "a WhatsApp message",
	sms: "a text message",
	email: "an email",
};

/** Access needs, as instructions rather than flags — the thing on the
 *  other end is a model reading a prompt, and this repo has learned
 *  twice that a rule the model never reads is a rule the output
 *  ignores. */
export const NEEDS = {
	"audio-only": "everything must work without sight",
	"large-text": "any visual output must be large and high-contrast",
	"slow-speech": "speak slowly, and leave room for an answer",
	"simple-language": "short sentences, no jargon, one idea at a time",
	reintroduce: "say who is calling, every time",
};

export const DEFAULT_WAKING_HOURS = [9, 20];

/**
 * May this contact happen? Returns [allowed, why].
 *
 * Checked in the order a person would care about, so the reason logged
 * is the reason that mattered. The recipient's own refusal comes FIRST,
 * before the signature is even looked at: a system that verifies a
 * guardian's key before it will stop ringing a frightened person has
 * its priorities inverted.
 *
 * `verifyBytes` is optional and asynchronous here, unlike the Python,
 * because WebCrypto is. When it is absent the check degrades to "is
 * there a signature at all" — the same degradation the Python makes,
 * and the same one that means a real deployment must pass it.
 */
export async function mayContact(signedConsent, {
	channel, purpose, nowIso, localHour,
	contactsToday = 0, recipientSaidStop = false, revoked = false,
	verifyRecord = null,
} = {}) {
	// 1. The person on the other end. No signature, no key, no appeal.
	if (recipientSaidStop) return [false, "the recipient asked us to stop"];

	// 2. The guardian took it back.
	if (revoked) return [false, "this consent was withdrawn"];

	const body = (signedConsent || {}).record || {};
	if (body.kind !== "consent") return [false, "not a consent record"];

	// 3. Is it real? A record we cannot verify is a record we did not
	//    get, and this is the one place failing open would be indefensible.
	if (verifyRecord) {
		const [ok, why] = await verifyRecord(signedConsent);
		if (!ok) return [false, `consent does not verify — ${why}`];
	} else if (signedConsent.signature === null || signedConsent.signature === undefined) {
		return [false, "consent is unsigned"];
	}

	// 4. Still current. Lexicographic compare is correct for ISO-8601
	//    UTC and avoids a date library on both sides of the port.
	if (!body.expires_at || nowIso >= body.expires_at) return [false, "consent has expired — ask again"];

	// 5. What was actually agreed to.
	if (!(body.channels || []).includes(channel)) {
		return [false, `${CHANNELS[channel] || channel} was not agreed to`];
	}
	if (!(body.purposes || []).includes(purpose)) {
		return [false, `'${purpose}' is not a purpose this consent covers`];
	}

	// 6. Not in the middle of the night.
	const [start, end] = body.waking_hours || DEFAULT_WAKING_HOURS;
	if (!(localHour >= start && localHour < end)) {
		return [false, `outside waking hours (${start}:00-${end}:00 where they are)`];
	}

	// 7. Not again and again. Someone who cannot remember the last call
	//    experiences the fourth one as the first, which is worse.
	const ceiling = body.max_contacts_per_day ?? 2;
	if (contactsToday >= ceiling) {
		return [false, `already contacted ${contactsToday} times today (limit ${ceiling})`];
	}

	return [true, "permitted"];
}

export function needsOf(signedConsent) {
	return [...(((signedConsent || {}).record || {}).needs || [])];
}

/** The access needs as an instruction, for whatever speaks. */
export function briefFor(signedConsent) {
	const lines = needsOf(signedConsent).filter((n) => n in NEEDS).map((n) => NEEDS[n]);
	if (!lines.length) return "";
	return `The person you are speaking to needs you to: ${lines.join("; ")}.`;
}
